console.log(location.href);
console.log(location.protocol);
console.log(location.hostname);
console.log(location.port);
console.log(location.pathname);
console.log(location.hash);
console.log(location.origin);
console.log(location.search);
console.log(location.host);